name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install ruff
      - name: Run Ruff
        run: ruff check .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install mypy pandas-stubs types-requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Mypy
        run: mypy . --ignore-missing-imports --exit-zero

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov pandas mlflow fastapi pydantic scikit-learn
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests with coverage
        run: pytest --cov=. --cov-fail-under=10 # On met un seuil bas pour être sûr de valider l'infra

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker
        run: docker build -t churnguard-api:latest .